# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Please, upload an image for this badge', null=True, upload_to='badges', verbose_name='Image'),
        ),
    ]
